import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ArrowUpRight, Building2, Check, ChevronRight, Download, FileText, Home, Layers, MapPin, MessageCircle, PanelsTopLeft, Store } from "lucide-react";
import { getDeveloper, getProject, getProjectUnits, projects } from "@/data/marketplace";
import { MediaGallery } from "@/components/marketplace/gallery";
import { CurrentInventory } from "@/components/marketplace/current-inventory";
import { Inventory } from "@/components/marketplace/inventory";
import { RahatHeightsFeatures } from "@/components/marketplace/rahat-heights-features";
import { projectWhatsappLink } from "@/lib/whatsapp";
import { breadcrumbJsonLd, jsonLdScript, pageMetadata } from "@/lib/seo";
import styles from "@/components/marketplace/project-detail.module.css";
export function generateStaticParams() { return projects.map((project) => ({ slug: project.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
    const project = getProject((await params).slug);
    if (!project) return {};
    const developer = getDeveloper(project.developerId);
    return pageMetadata({ title: project.name, description: `Explore ${project.name}${developer ? ` by ${developer.name}` : ""} in ${project.address}. ${project.categories.join(", ")}. View project details, published plans and enquiry options through SAFIZMARKETING.`, path: `/projects/${project.slug}` });
}
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
    const project = getProject((await params).slug);
    if (!project) notFound();
    const developer = getDeveloper(project.developerId)!;
    const units = getProjectUnits(project.id);
    const plan = project.paymentPlan;
    const whatsapp = projectWhatsappLink(project);
    const categories = [
        { label: "Shops", icon: Store, image: "/images/type-commercial.jpg", copy: "Commercial spaces for your next business move.", type: units.some((unit) => unit.type === "shop-office") ? "shop-office" : "shop", match: /shop/i },
        { label: "Offices", icon: Building2, image: "/images/property-02.jpg", copy: "Explore spaces for work and business.", type: "office", match: /office/i },
        { label: "Apartments", icon: Home, image: "/images/gallery-living.jpg", copy: "Discover residential spaces in the project.", type: "apartment", match: /apartment|penthouse/i },
    ].filter((item) => project.categories.some((category) => item.match.test(category)));
    return <div className={`${styles.page} ${project.slug === "rahat-heights" ? styles.rahatPage : ""}`}>
        <section className={styles.hero}><Image src={project.cover.src} alt={project.cover.alt} fill sizes="100vw" preload className={styles.heroImage} /><div className={styles.heroShade} /><div className="rh-container"><div className={styles.heroCopy}>
            <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight size={12} /><Link href="/projects">Projects</Link><ChevronRight size={12} /><span aria-current="page">{project.name}</span></nav><p className={styles.eyebrow}>{project.projectType} Project</p><h1>{project.name}</h1><p>{project.description[0]}</p><div className={styles.heroLocation}><MapPin size={16} />{project.address}</div><div className={styles.heroTags}>{project.categories.map((category) => <span key={category}>{category}</span>)}</div><div className={styles.actions}><a className={styles.goldButton} href="#inventory">Explore Inventory<ArrowRight size={15} /></a><a className={styles.lightOutlineButton} href={project.brochure} target="_blank" rel="noopener noreferrer"><FileText size={16} />Get Brochure</a></div>
        </div></div><span className={styles.imageNote}>Developer concept render · indicative imagery</span></section>
        <section className={styles.facts}><div className="rh-container"><div><Building2 /><p><span>Developer</span><Link href={`/developers/${developer.slug}`}>{developer.name}</Link></p></div><div><MapPin /><p><span>Location</span><strong>{project.address}</strong></p></div><div><PanelsTopLeft /><p><span>Property Type</span><strong>{project.categories.join(" · ")}</strong></p></div><div><Layers /><p><span>Payment Plan</span><strong>{plan ? `${plan.downPercent}% Down Payment` : "Enquire for Details"}</strong>{plan && <small>{plan.count} Quarterly Installments</small>}</p></div><div><FileText /><p><span>Price List</span>{plan ? <a href={plan.source} target="_blank" rel="noopener noreferrer">Published Developer Plan</a> : <strong>Enquire for Current Pricing</strong>}</p></div></div></section>
        <section className={styles.overview} id="overview"><div className="rh-container"><div><p className={styles.eyebrow}>Project Overview</p><h2>{project.overview}</h2>{project.description.map((paragraph) => <p className={styles.copy} key={paragraph}>{paragraph}</p>)}<div className={styles.overviewFeatures}><span><MapPin />{project.city}</span><span><Building2 />{project.projectType}</span><span><Store />Commercial & Residential</span><span><FileText />Published Project Material</span></div></div><div className={styles.overviewImage}><Image src={project.cover.src} alt={project.cover.alt} fill sizes="(min-width: 1000px) 28vw, 90vw" /></div><aside className={styles.developer}><div>{developer.logo && <Image src={developer.logo.src} alt={developer.logo.alt} width={51} height={55} />}<div><p className={styles.eyebrow}>A Project By</p><h3>{developer.name}</h3></div></div><p>{developer.overview}</p><Link className={styles.navyButton} href={`/developers/${developer.slug}`}>View Developer Profile<ArrowRight size={15} /></Link></aside></div></section>
        <section className={styles.explore}><div className="rh-container"><p className={styles.eyebrow}>Explore Inventory</p><h2>Find the right space for your goals.</h2><p className={styles.copy}>Explore the property types described in the developer’s project material.</p><div className={styles.categoryGrid}>{categories.map((category) => <Link key={category.label} href={`/properties?project=${project.id}&type=${category.type}`}><Image src={category.image} alt={`${category.label}; illustrative editorial photography`} fill sizes="(min-width: 1000px) 30vw, 90vw" /><div><category.icon size={28} /><div><h3>{category.label}</h3><p>{category.copy}</p></div><ArrowRight size={18} /></div></Link>)}</div></div></section>
        {project.slug === "rahat-heights" ? <CurrentInventory units={units} /> : <section className={styles.payment} id="inventory"><div className="rh-container"><div className={styles.paymentHead}><div><p className={styles.eyebrow}>Payment Plan & Price List</p><h2>The numbers, in detail.</h2><p>{plan ? plan.sourceLabel : "Contact our team for the current published price list and payment terms."}</p></div>{plan && <div className={styles.planStats}><div><strong>{plan.downPercent}%</strong><span>Down Payment</span></div><div><strong>{plan.count}</strong><span>Quarterly Installments</span></div><a href={plan.source} target="_blank" rel="noopener noreferrer"><Download size={22} /><div><strong>Price List</strong><span>View Original PDF</span></div></a></div>}</div>
            {units.length ? <><div className={styles.inventoryPanel}>{plan && <a className={styles.download} href={plan.source} target="_blank" rel="noopener noreferrer"><Download size={14} />Download Price List</a>}<Inventory units={units} /></div>{plan?.note && <p className={styles.paymentNote}>{plan.note}</p>}<p className={styles.paymentNote}>Published developer figures. Contact SAFIZ MARKETING to confirm current availability, pricing and terms.</p></> : <div className={styles.unpublished}><FileText size={28} /><div><h3>Unit pricing is available by enquiry.</h3><p>A current unit schedule has not been supplied for this project.</p></div><a className={styles.goldButton} href={whatsapp} target="_blank" rel="noopener noreferrer">Ask About Pricing<ArrowRight size={15} /></a></div>}
        </div></section>}
        {project.slug === "rahat-heights" ? <RahatHeightsFeatures /> : <section className={styles.amenities} id="features"><div className="rh-container"><div><p className={styles.eyebrow}>Amenities</p><h2>Designed around<br />daily life.</h2><p className={styles.copy}>Features described in the developer’s brochure.</p></div><ul>{project.amenities.map((amenity) => <li key={amenity}><span><Check size={22} /></span>{amenity}</li>)}</ul></div></section>}
        <section className={styles.plans} id="floor-plans"><div className="rh-container"><div><p className={styles.eyebrow}>Floor Plans</p><h2>{project.slug === "rahat-heights" ? "See how the space comes together." : <>See how the space<br />comes together.</>}</h2><p className={styles.copy}>Open a developer-supplied plan to inspect the layout.</p></div><div className={styles.planGallery}><MediaGallery items={project.floorPlans} label={`${project.name} floor plans`} plans /></div></div></section>
        {project.slug === "rahat-heights" && <section className={styles.interiors} id="interior-concepts" aria-labelledby="interior-concepts-heading"><div className="rh-container"><div className={styles.interiorsHead}><div><p className={styles.eyebrow}>Interior Concepts</p><h2 id="interior-concepts-heading">A closer look at the interiors.</h2></div><p className={styles.copy}>Bedroom, living, kitchen and bathroom concepts from pages 10–13 of the developer brochure. Open an image to view the complete page.</p></div><div className={styles.interiorsGallery}><MediaGallery items={[
            { src: "/projects/rahat-heights-page-10.jpg", width: 1600, height: 1095, alt: "Bedroom concepts · Brochure page 10" },
            { src: "/projects/rahat-heights-page-11.jpg", width: 1600, height: 1095, alt: "Living room concepts · Brochure page 11" },
            { src: "/projects/rahat-heights-page-12.jpg", width: 1600, height: 1095, alt: "Kitchen concepts · Brochure page 12" },
            { src: "/projects/rahat-heights-page-13.jpg", width: 1600, height: 1095, alt: "Bathroom concepts · Brochure page 13" },
        ]} label="Rahat Heights interior concepts from brochure pages 10–13" plans /></div></div></section>}
        {project.locationMap && <section className={styles.location} id="location"><div className="rh-container"><div><p className={styles.eyebrow}>Location & Access</p><h2>A prime address<br />in {project.city}.</h2><p className={styles.copy}>{project.address}. Explore the location material supplied in the project brochure.</p><a className={styles.goldButton} href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(project.address)}`} target="_blank" rel="noopener noreferrer">View on Google Maps<ArrowRight size={14} /></a></div><div className={styles.locationMap}><MediaGallery items={[project.locationMap]} label={`${project.name} location map`} plans /></div><aside><h3>Project Location</h3><p><MapPin size={17} />{project.address}</p><h3>Plan a Site Visit</h3><p>Contact our team to confirm directions, access and current project details.</p><a href={whatsapp} target="_blank" rel="noopener noreferrer">Ask About This Location<ArrowUpRight size={14} /></a></aside></div></section>}
        <section className={styles.gallery} id="gallery"><div className="rh-container"><div><p className={styles.eyebrow}>Project Gallery</p><h2>{project.slug === "rahat-heights" ? "The place behind the project." : <>The place behind<br />the project.</>}</h2><p className={styles.copy}>Concept imagery and project material from the developer brochure.</p></div><div className={styles.galleryImages}><MediaGallery items={project.gallery} label={`${project.name} project gallery`} /></div></div></section>
        <section className={styles.related}><div className="rh-container"><div><p className={styles.eyebrow}>Related Projects</p><h2>{project.slug === "rahat-heights" ? `Explore more by ${developer.name}.` : <>Explore more by<br />{developer.name}.</>}</h2><p className={styles.copy}>Discover other listed developments.</p></div><div className={styles.relatedGrid}>{projects.filter((item) => item.id !== project.id && item.developerId === developer.id).map((item) => <Link key={item.id} href={`/projects/${item.slug}`}><div className={styles.relatedImage}><Image src={item.cover.src} alt={item.cover.alt} fill sizes={project.slug === "rahat-heights" ? "(min-width: 750px) 44vw, 90vw" : "160px"} /></div><div><h3>{item.name}</h3><p>{item.address}</p><span>View Project<ArrowRight size={13} /></span></div></Link>)}</div></div></section>
        <section className={styles.cta}><div className="rh-container"><div><h2>A better property conversation.</h2><p>Talk to our team for inventory, payment plans or a site visit.</p></div><div className={styles.actions}><a className={styles.goldButton} href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={16} />Chat on WhatsApp<ArrowRight size={14} /></a><Link className={styles.outlineButton} href="/contact">Get in Touch<ArrowRight size={14} /></Link></div></div></section>
        <script type="application/ld+json" dangerouslySetInnerHTML={jsonLdScript(breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Projects", path: "/projects" }, { name: project.name, path: `/projects/${project.slug}` }]))} />
    </div>;
}
